version: '3.8'

services:
  # Сервис Mongo DB
  mongo-server:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # Сервис вашего приложения на Go
  service-app:
    build: .
    container_name: service_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      test_env: "hello"
    depends_on:
      - mongo-server
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
