name: Docker Compose Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Скачиваем свежий код
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Сборка и деплой
      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up --build -d
